apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend-container
          image: docker.io/slyohmy/frontend:latest
          ports:
            - containerPort: 4200
          resources: {}
      restartPolicy: Always
status: {}
